# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master


jobs:
- job:
  displayName: "Build Flatpak Docker Image"
  pool:
    vmImage: 'Ubuntu-16.04'
  variables:
    - group: passwords
  steps:
    - script: |
        docker build -t mobsya/flatpak-builders:kde-latest .
        docker login -u cor3ntinmobsya -p $(corentin-docker)
        docker push mobsya/flatpak-builders
      workingDirectory: flatpak
      displayName: "Build Flatpak image"

- job:
  displayName: "Build Linux Dev Environment Docker Image"
  pool:
    vmImage: 'Ubuntu-16.04'
  variables:
  - group: passwords
  steps:
    - script: |
        docker build -t mobsya/linux-dev-env:latest .
        docker login -u cor3ntinmobsya -p $(corentin-docker)
        docker push mobsya/linux-dev-env
      workingDirectory: linux_dev_env
      displayName: "Build Linux Dev Env image"


- job:
  timeoutInMinutes: 360
  displayName: "Build Windows Dev Environment Docker Image"
  pool:
    vmImage: 'win1803'
  variables:
  - group: passwords
  steps:
    - script: |
        echo "$(corentin-docker)" | docker login --username cor3ntinmobsya --password-stdin
        docker build -t mobsya/windows-dev-env:latest .
        echo "$(corentin-docker)" | docker login --username cor3ntinmobsya --password-stdin
        docker push mobsya/windows-dev-env
      workingDirectory: windows_dev_env
      displayName: "Build Windows Dev Env image"