ARG QT_API_LEVEL
ARG THYMIO_API_LEVEL
ARG NDK_VERSION
ARG NDK_VERSION
ARG QT_BASE_VERSION
ARG QT_PATCH_NUMBER

FROM mobsya/qt-builder:android${QT_API_LEVEL}-ndk${NDK_VERSION}-qt${QT_BASE_VERSION}.${QT_PATCH_NUMBER} as qt

FROM mobsya/android-sdk:android${THYMIO_API_LEVEL}-ndk${NDK_VERSION}
COPY --from=qt /qt /qt


# Required for compiling custom CMake (libssl-dev) or required to build Thymio Suite
RUN apt update && apt install -y -q libssl-dev python3 ninja-build && rm -rf /var/lib/apt/lists/*

# Install CMake >= 3.13 (minimum required version).
RUN wget https://github.com/Kitware/CMake/releases/download/v3.18.4/cmake-3.18.4.tar.gz \
    && tar -zxvf cmake-3.18.4.tar.gz \
    && cd cmake-3.18.4 \
    && ./bootstrap \
    && make -j$(nproc) \
    && make install \
    && cd .. \
    && rm -R cmake-3.18.4

WORKDIR /src
VOLUME /src
VOLUME /build

ENV QT_ANDROID_SDK_ROOT=${ANDROID_SDK_PATH}
ENV ANDROID_SDK=${ANDROID_SDK_PATH}
ENV ANDROID_NDK=${ANDROID_NDK_PATH}

ARG THYMIO_API_LEVEL
ENV API_LEVEL ${THYMIO_API_LEVEL}
ARG NDK_VERSION
ENV NDK_VERSION ${NDK_VERSION}
ARG QT_BASE_VERSION
ARG QT_PATCH_NUMBER
ENV QT_VERSION ${QT_BASE_VERSION}.${QT_PATCH_NUMBER}

ENTRYPOINT ["/bin/bash", "-c"]
CMD ["echo === Qt development environment for Android: API_LEVEL=$API_LEVEL, NDK_VERSION=$NDK_VERSION, QT_VERSION=$QT_VERSION ===; echo ; cmake --version; echo Ninja $(ninja --version); echo QT_ANDROID_SDK_ROOT: $QT_ANDROID_SDK_ROOT; echo ANDROID_SDK, ANDROID_SDK_PATH: $ANDROID_SDK_PATH; echo ANDROID_NDK, ANDROID_NDK_PATH: $ANDROID_NDK_PATH"]
